version: '3.7'

services:

  # Nginx
  nginx:
    image: ${REPOSITORY_URL}/${NGINX_IMAGE_NAME}:${IMAGE_TAG}
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - VIRTUAL_PORT=${APP_PORT}
      - VIRTUAL_PROTO=https
      - VIRTUAL_NETWORK=proxy
      - LETSENCRYPT_HOST=${APP_HOST}
      - LETSENCRYPT_EMAIL=${CERT_EMAIL}
    volumes:
      - ${SOURCE_PATH}/storage:${APP_PATH}/storage
      - ../log/nginx/:/var/log/nginx
      - ../etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../etc/nginx/site.conf.tmpl:/etc/nginx/site.conf.tmpl
      - ../certs:/etc/nginx/certs:rw
      - /etc/nginx/sites-available
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  # PHP
  php:
    image: ${REPOSITORY_URL}/${PHP_IMAGE_NAME}:${IMAGE_TAG}
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_TIMEZONE=${APP_TIMEZONE}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - LOG_DEPRECATIONS_CHANNEL=${LOG_DEPRECATIONS_CHANNEL}
      - LOG_LEVEL=${LOG_LEVEL}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_CHARSET=${DB_CHARSET}

      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - FILESYSTEM_DISK=${FILESYSTEM_DISK}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}

      - MEMCACHED_HOST=${MEMCACHED_HOST}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}

      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      - MAIL_TO_ADDRESS=${MAIL_TO_ADDRESS}
      - MAIL_TO_NAME=${MAIL_TO_NAME}

      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_USE_PATH_STYLE_ENDPOINT=${AWS_USE_PATH_STYLE_ENDPOINT}

      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}

      - MIX_PUSHER_APP_KEY=${MIX_PUSHER_APP_KEY}
      - MIX_PUSHER_APP_CLUSTER=${MIX_PUSHER_APP_CLUSTER}

      - MEDIA_DISK=${MEDIA_DISK}
      - MEDIA_PREFIX=${MEDIA_PREFIX}
    volumes:
      - ${SOURCE_PATH}/storage:${APP_PATH}/storage
      - ${SOURCE_PATH}/bootstrap/cache:${APP_PATH}/bootstrap/cache

  # Artisan
  artisan:
    extends:
      service: php
    container_name: ${COMPOSE_PROJECT_NAME}-artisan
    restart: "no"
    entrypoint: php artisan
