version: '3.7'

services:

  # Database
  db:
    image: postgres:12.1-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db
    restart: always
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
      - ../sql/:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s

  # Nginx
  nginx:
    build:
      context: nginx
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    command: /bin/bash -c "envsubst '$$NGINX_PORT $$NGINX_ROOT $$NGINX_HOST $$PHP_HOST $$PHP_PORT' < /etc/nginx/site.conf.tmpl > /etc/nginx/sites-available/site.conf && nginx -g 'daemon off;'"
    restart: always
    expose:
      - ${APP_PORT}
    working_dir: /etc/nginx
    environment:
      #      - VIRTUAL_HOST=${APP_HOST}
      #      - VIRTUAL_PORT=${APP_PORT}
      #      - VIRTUAL_PROTO=https
      #      - VIRTUAL_NETWORK=proxy
      #      - SELF_SIGNED_HOST=${APP_HOST}
      - NGINX_ROOT=${APP_PATH}
      - NGINX_HOST=${APP_HOST}
      - NGINX_PORT=${APP_PORT}
      - PHP_HOST=${PHP_HOST}
      - PHP_PORT=${PHP_PORT}
    depends_on:
      - php
    links:
      - php:${PHP_HOST}
    networks:
      - proxy
      - default
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 5s

  # PHP
  php:
    build:
      context: php-fpm
      target: php
      args:
        - UID=${UID}
        - GID=${GID}
        - INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}
        - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
    container_name: ${COMPOSE_PROJECT_NAME}-php
    restart: always
    expose:
      - ${PHP_PORT}
    user: ${UID}:${GID}
    working_dir: ${APP_PATH}
    environment:
      - UID=${UID}
      - GID=${GID}
      - XDEBUG_MODE=${PHP_XDEBUG_MODE:-off}
    #      - XDEBUG_CONFIG=${PHP_XDEBUG_CONFIG:-client_host=host.docker.internal}
    depends_on:
      - db
    links:
      - db:${DB_HOST_MAIN}
      - redis:${REDIS_HOST}
      - elasticsearch:${ELASTIC_SEARCH_HOST}
    healthcheck:
      test: healthcheck || echo 1
      interval: 5s

  # Artisan
  artisan:
    extends:
      service: php
    container_name: ${COMPOSE_PROJECT_NAME}-artisan
    restart: "no"
    entrypoint: php artisan

  # Redis
  redis:
    image: redis:6.2.6-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s

volumes:
  db:

networks:
  proxy:
    name: proxy
    external: true
